### ISSUE TITLE
iPhone12：视频导出有声音、画面蓝屏的bug

### ISSUE THREAD

**Issue by GTZhangPing** [banchichen/TZImagePickerController#1427]
**提bug前必看**
请先回答下列三个问题，否则不允处理，谢谢配合。
1、我最新的Demo是否有这个bug？【**如果Demo没问题，请升级新版**】
答：是

2、你用的是什么版本？升级到最新版后是否正常？
答：最新版 3.4.8 存在这个问题

3、是否有改动过我库内部的代码？【**如有，请告诉我你改了什么**】
答：未改动

**bug内容描述**
iPhone12 用相机拍视频然后导出，有声音、画面蓝屏
其他手机这样操作正常

iPhone12 直接从app 拍视频然后导出视屏，正常
其他手机也正常

**我如何复现这个bug？**
iPhone12 用相机拍视频然后导出，有声音、画面蓝屏

**截图**
![image](https://user-images.githubusercontent.com/18136388/100401608-efb76a00-3094-11eb-936e-54060779cad8.png)

**其它说明**
有没有其它要补充的？比如你的初始化TZImagePickerController的代码

**Comment by banchichen** [comment]
最新版是3.5.4哈，试一下最新的demo是否正常哈

**Comment by rryan2** [comment]
升级到3.5.4也有这个问题

**Comment by rryan2** [comment]
3.5.4还是有这个问题

**Comment by kyleSmart** [comment]
AVAssetExportPresetMediumQuality 和 AVAssetExportPresetLowQuality都会出现蓝屏的。AVAssetExportPreset640x480这个我试了是可以的

**Comment by WHChaw** [comment]
我也遇到了这个问题，iPhone12 pro max上用系统相机录制视频，然后在app中选取视频出现蓝屏问题，其他机型未出现问题

**Comment by banchichen** [comment]
基本确定是系统bug：
https://discussions.apple.com/thread/251957053
https://stackoverflow.com/questions/65288788/iphone-12-compression-of-video-making-videos-blue-colored

可以验证下这样设置后是否解决，以合适的方式告知用户这样设置：
Go to Settings. Search Camera.
Go to FORMATS, change to Most Compatible instead of High Efficiency.

也可以试试这个绕过方案：https://www.jianshu.com/p/71ba1fd93313

**Comment by Zeta-XL** [comment]
iOS 14.3 好像修复了这个问题，谁有iPhone12 可以升级后确认一下

**Comment by wangshaoren** [comment]
> iOS 14.3 好像修复了这个问题，谁有iPhone12 可以升级后确认一下

我这边iPhone12 14.2会有这个问题，iPhone12  14.3没有这个问题了，系统应该是已经修复了这个bug。
