### ISSUE TITLE
How to disable photo scale?

### ISSUE THREAD

**Issue by balkarov** [banchichen/TZImagePickerController#475]
Hello!
Thank you for your library.

I want get only original photo. But always I get scale photo. How to fix it.
In library I remove this line (below) and work for me. But how fix it without change library code?
`photo = [self scaleImage:photo toSize:CGSizeMake(tzImagePickerVc.photoWidth, (int)(tzImagePickerVc.photoWidth * photo.size.height / photo.size.width))];`

**Comment by banchichen** [comment]
Hello, in order to avoid memory surge, the photo in photos array always is thumbnail.
If user selects the original photo, isSelectOriginalPhoto will be YES, then you need to get the original image by the asset, through the method of the TZImageManager class:

> /// Get original Image 
- (void)getOriginalPhotoWithAsset:(id)asset completion:(void (^)(UIImage *photo,NSDictionary *info))completion;

completion may be called 1 or more times.
if info[PHImageResultIsDegradedKey] is YES, the photo is thumbnail,  otherwise the photo is original photo
